import json

HEADER = """// this file is generated by program
// please do not modify this file

const TRANS_KEYS = [
"""

FOOTER = """];

export { TRANS_KEYS };
"""

LINE = '  "%s",\n'

IN_FILE = "_locales/en/messages.json"
OUT_FILE = "js/trans-keys.js"

if __name__ == "__main__":
  with open(IN_FILE, "r") as inFile:
    obj = json.load(inFile)

  with open(OUT_FILE, "w") as out:
    out.write(HEADER)
    for key in obj.keys():
      out.write(LINE % key)
    out.write(FOOTER)
