import json
import os
import shutil
from datetime import datetime
HEADER = """// this file is generated by program
// please do not modify this file

const TRANS_KEYS = [
"""

FOOTER = """];

export { TRANS_KEYS };
"""

LINE = '  "%s",\n'

EN_FILE = "_locales/en/messages.json"
ZH_CN_FILE = "_locales/zh_CN/messages.json"
ZH_CN_BACKUP = "_locales/zh_CN/.backup.messages%s.json"
OUT_FILE = "js/trans-keys.js"

if __name__ == "__main__":
  # load keys
  with open(EN_FILE, "r") as inFile:
    enTrans = json.load(inFile)

  # generate key lists file
  with open(OUT_FILE, "w") as out:
    out.write(HEADER)
    for key in enTrans.keys():
      out.write(LINE % key)
    out.write(FOOTER)
  
  print("key list generated.")

  # load zh-CN keys
  with open(ZH_CN_FILE, "r", encoding="utf8") as inFile:
    zhCnTrans = json.load(inFile)
  
  # add absent keys
  keyDiff = set(enTrans.keys()).difference(zhCnTrans.keys())
  if len(keyDiff) > 0:
    print("absent keys: ", keyDiff)
    for key in keyDiff:
      zhCnTrans[key] = enTrans[key]
    # backup before overwrite
    backUpFilename = ZH_CN_BACKUP % datetime.now().strftime("%Y%m%d-%H%M%S")
    shutil.copy(ZH_CN_FILE, backUpFilename)
    print("backup original file at", backUpFilename)
    with open(ZH_CN_FILE, "w", encoding="utf8") as outFile:
      json.dump(zhCnTrans, outFile, ensure_ascii=False, indent=2)
  else:
    print("No absent key in zh-CN")
  
  print("Done")